"""Scenario configuration for multi-agent simulations."""
from .personas import (
    PERSONAS,
    get_persona,
    get_personas_by_category,
    get_personas_by_stance,
    get_opposing_personas,
    get_related_personas,
    create_debate_pair,
    list_all_personas,
)
from .tech_tree import (
    TechCategory,
    TechTier,
    Technology,
    TECH_TREE,
    CURRENT_WORLD_UNLOCKED,
    ORG_TECH_ACCESS,
    get_tech,
    get_prerequisites,
    get_unlocked_by,
    get_tier,
    get_category,
    can_research,
    get_available_research,
    get_tech_path,
    compute_total_cost,
)
from .schema import (
    # Knob 1: Personas
    PersonaCategory,
    PersonaStance,
    PersonaConfig,
    # Knob 2: Strategy
    ReasoningStrategy,
    PersuasionTactic,
    StrategyConfig,
    # Knob 3: World State
    TechLevel,
    PolicyStatus,
    PolicyConfig,
    TechnologyConfig,
    ResourcePool,
    WorldStateConfig,
    # Knob 4: Models
    ModelProvider,
    ModelConfig,
    MODELS,
    # Agent & Event
    AgentConfig,
    EventType,
    EventTrigger,
    EventConfig,
    # Communication
    CommunicationMode,
    CommunicationConfig,
    # Main schema
    ScenarioConfig,
    # Pre-built scenarios
    create_xi_elon_scenario,
    create_xrisk_debate_scenario,
)

__all__ = [
    # Personas
    "PERSONAS",
    "get_persona",
    "get_personas_by_category",
    "get_personas_by_stance",
    "get_opposing_personas",
    "get_related_personas",
    "create_debate_pair",
    "list_all_personas",
    # Tech tree
    "TechCategory",
    "TechTier",
    "Technology",
    "TECH_TREE",
    "CURRENT_WORLD_UNLOCKED",
    "ORG_TECH_ACCESS",
    "get_tech",
    "get_prerequisites",
    "get_unlocked_by",
    "get_tier",
    "get_category",
    "can_research",
    "get_available_research",
    "get_tech_path",
    "compute_total_cost",
    # Schema
    "PersonaCategory",
    "PersonaStance",
    "PersonaConfig",
    "ReasoningStrategy",
    "PersuasionTactic",
    "StrategyConfig",
    "TechLevel",
    "PolicyStatus",
    "PolicyConfig",
    "TechnologyConfig",
    "ResourcePool",
    "WorldStateConfig",
    "ModelProvider",
    "ModelConfig",
    "MODELS",
    "AgentConfig",
    "EventType",
    "EventTrigger",
    "EventConfig",
    "CommunicationMode",
    "CommunicationConfig",
    "ScenarioConfig",
    "create_xi_elon_scenario",
    "create_xrisk_debate_scenario",
]
